version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: zht
      POSTGRES_PASSWORD: 1873
      POSTGRES_DB: E-Commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  inventory-service:
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: "postgresql://zht:1873@postgres:5432/E-Commerce?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "50051:50051"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: "postgresql://zht:1873@postgres:5432/E-Commerce?sslmode=disable"
    depends_on:
      - postgres
      - inventory-service
    ports:
      - "50052:50052"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - inventory-service
      - order-service
    ports:
      - "8080:8080"

volumes:
  postgres_data: