// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: producer-service/proto/producer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductIds    []string               `protobuf:"bytes,2,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedRequest) Reset() {
	*x = OrderCreatedRequest{}
	mi := &file_producer_service_proto_producer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedRequest) ProtoMessage() {}

func (x *OrderCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_producer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedRequest.ProtoReflect.Descriptor instead.
func (*OrderCreatedRequest) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_producer_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreatedRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreatedRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type OrderCreatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedResponse) Reset() {
	*x = OrderCreatedResponse{}
	mi := &file_producer_service_proto_producer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedResponse) ProtoMessage() {}

func (x *OrderCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_producer_service_proto_producer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedResponse.ProtoReflect.Descriptor instead.
func (*OrderCreatedResponse) Descriptor() ([]byte, []int) {
	return file_producer_service_proto_producer_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreatedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_producer_service_proto_producer_proto protoreflect.FileDescriptor

const file_producer_service_proto_producer_proto_rawDesc = "" +
	"\n" +
	"%producer-service/proto/producer.proto\x12\bproducer\"Q\n" +
	"\x13OrderCreatedRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\tR\n" +
	"productIds\"0\n" +
	"\x14OrderCreatedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2f\n" +
	"\x0fProducerService\x12S\n" +
	"\x12NotifyOrderCreated\x12\x1d.producer.OrderCreatedRequest\x1a\x1e.producer.OrderCreatedResponseB#Z!E-Commerce/producer-service/protob\x06proto3"

var (
	file_producer_service_proto_producer_proto_rawDescOnce sync.Once
	file_producer_service_proto_producer_proto_rawDescData []byte
)

func file_producer_service_proto_producer_proto_rawDescGZIP() []byte {
	file_producer_service_proto_producer_proto_rawDescOnce.Do(func() {
		file_producer_service_proto_producer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_producer_service_proto_producer_proto_rawDesc), len(file_producer_service_proto_producer_proto_rawDesc)))
	})
	return file_producer_service_proto_producer_proto_rawDescData
}

var file_producer_service_proto_producer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_producer_service_proto_producer_proto_goTypes = []any{
	(*OrderCreatedRequest)(nil),  // 0: producer.OrderCreatedRequest
	(*OrderCreatedResponse)(nil), // 1: producer.OrderCreatedResponse
}
var file_producer_service_proto_producer_proto_depIdxs = []int32{
	0, // 0: producer.ProducerService.NotifyOrderCreated:input_type -> producer.OrderCreatedRequest
	1, // 1: producer.ProducerService.NotifyOrderCreated:output_type -> producer.OrderCreatedResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_producer_service_proto_producer_proto_init() }
func file_producer_service_proto_producer_proto_init() {
	if File_producer_service_proto_producer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_producer_service_proto_producer_proto_rawDesc), len(file_producer_service_proto_producer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_producer_service_proto_producer_proto_goTypes,
		DependencyIndexes: file_producer_service_proto_producer_proto_depIdxs,
		MessageInfos:      file_producer_service_proto_producer_proto_msgTypes,
	}.Build()
	File_producer_service_proto_producer_proto = out.File
	file_producer_service_proto_producer_proto_goTypes = nil
	file_producer_service_proto_producer_proto_depIdxs = nil
}
